### ISSUE TITLE
phyluce_assembly_get_trinity_coverage

### ISSUE THREAD

**Issue by zhangpizhu** [carloliveros/test#1]
Hello
 Dr Carloiveros. I have a problem when analyze UCEs datas follow your UCE pipeline. In step 6, I don't know what the configuration file of trinity like? Is like the configuration file in step 2 named"trinity-assemblies.conf"?

**Comment by carloliveros** [comment]
Yes. Use the same format as Step 2.  Note that a much updated pipeline is available in: https://phyluce.readthedocs.io/en/latest/tutorial-one.html

**Comment by zhangpizhu** [comment]
Thank you very much!
